Added support for Node2D and Control derived entities
QodotPlugin/Qodot pull request #85
Opened 2023-09-23 04:34 UTC by RhapsodyInGeek

I'm an idiot and accidentally deleted the original pull request for this.

I realized if you somehow decided to set up a Node2D or Control as an entity you'd end up with an error trying to apply a Vector3 value to a Vector2 property. Instead of blocking this possibility, I added a check to allow for Vector2 compatibility.

In Trenchbroom you position the 2D entity from the top down view. When built in Godot, the entity will be positioned according to the X and -Y origin values, eg: Vector3(64, -64, -1268) becomes Vector2(64, 64).

This will allow mappers to add things like per map UI elements or screen effects without needing to anchor them to a Node3D.

2023-09-23 05:14 UTC, EMBYRDEV requested changes
It looks like there is an errant print statement left in here.

2023-09-23 05:15 UTC, EMBYRDEV commented
Good idea! If you can remove the unneeded print then I'm happy to merge.

2023-09-23 11:33 UTC, RhapsodyInGeek reviewed
Removed the unnecessary print. Oops! I had just finished a working on the Skip fix from 9am to ~10pm, I was a little zonked out.

2023-10-03 04:45 UTC, EMBYRDEV commented
LGTM, Thanks!

2023-10-03 04:45 UTC, merged